### PR TITLE
i have made changes for  issue - 2023 Design 01 part 2 Multi Assigneest

### PR DESCRIPTION
**Pull request by Aka-suvam**
i  have done all the instructed changes .

### CODE REVIEW

**Comment by lmas3009** [comment]
can you share the final screenshot

**Comment by Aka-suvam** [comment]
Screenshot-2

**Comment by Aka-suvam** [comment]
Screenshot-2

**Comment by Aka-suvam** [comment]
Screenshot-2

**Comment by lmas3009** [comment]
Perfect 👍

**Comment by lmas3009** [comment]
Follow the folder naming condition

**Comment by lmas3009** [comment]
Design 01_2023/{your name}/your files

Your files will be index.html, css, etc..

**Comment by Aka-suvam** [comment]
Already done . just waitng for u to Pull Req 

Screenshot -3

**Comment by lmas3009** [comment]
It should be in this format
image

Because, for this issue many people can work on it

**Comment by Aka-suvam** [comment]
Thnks for the clarification. i will work on it now .

**Comment by Aka-suvam** [comment]
Hello imas . do i have to again raise Pull Req for adding folder Aka-suvam ? . because to make changes in the active  Pull req i getting option of only to add file not flolder.Can you guide or help in this .

**Comment by lmas3009** [comment]
Join this discord and ping me
https://discord.gg/C3PAvsmrKV

**Comment by Aka-suvam** [comment]
Hello  Imas i have done the changes . you can review it .

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Comment by Aka-suvam** [comment]
Thank u Imas for Guiding me .

**Pull request merged**
