### PR TITLE
Added Design 59

### PR DESCRIPTION
**Pull request by sumit-022**
Made design 59 according to the design shown in the image

### CODE REVIEW

**Comment by sumit-022** [comment]
@lmas3009 Please review this. I have made Design 59

**Comment by lmas3009** [comment]
Can you share ht result screenshot

**Comment by sumit-022** [comment]
@lmas3009 Here is the screenshot of what I have made
Screenshot (2)

**Comment by lmas3009** [comment]
Great work @sumit-022. It's looking good. 
Thanks for your contribution to this repo 🤝

**Pull request merged**
