### PR TITLE
Created logo using html css

### PR DESCRIPTION
**Pull request by manipta**

### CODE REVIEW

**Review by manipta — COMMENTED** [review]
I have checked all code is working

**Review by manipta — COMMENTED** [review]
all working good

**Review by manipta — COMMENTED** [review]
reviewed

**Comment by lmas3009** [comment]
Can you add issue id

**Comment by Esha-01** [comment]
Issue #6

**Comment by lmas3009** [comment]
@Esha-01 i think you mentioned wrong issue id

**Comment by lmas3009** [comment]
Looking Good @manipta. Thanks for contribution🤝

**Comment by lmas3009** [comment]
Merged

**Comment by manipta** [comment]
> Looking Good @manipta. Thanks for contribution🤝

Sorry for late reply. thank you for merging :)

**Pull request merged**
