### PR TITLE
Design-45-2023

### PR DESCRIPTION
**Pull request by dakshsinghrathore**
This PR solves issue #197 
Kindly review the PR and merge it under the hacktoberfest-accepted label tag if it's good to go !

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you share the result screenshot

**Comment by dakshsinghrathore** [comment]
@lmas3009 Sure 

image

**Comment by lmas3009** [comment]
Perfect
Thanks for contribution

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
