### PR TITLE
Design 21_2023

### PR DESCRIPTION
**Pull request by SamuelWoniowei**
This PR contains design 21

### CODE REVIEW

**Comment by lmas3009** [comment]
screenshot of your output

**Comment by SamuelWoniowei** [comment]
Screenshot 2023-10-02 at 08 35 42

**Comment by lmas3009** [comment]
perfect 👍

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
