### PR TITLE
Design 25_2023 done

### PR DESCRIPTION
**Pull request by NyanCyanide**

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you share the result screenshot

**Comment by NyanCyanide** [comment]
image
Here is the Result Screenshot

**Comment by lmas3009** [comment]
radius for the right image will be 100%. It should look like a capsule, not like a rectangle.

**Comment by lmas3009** [comment]
second image is okay

**Comment by NyanCyanide** [comment]
image
Fixed the right image from rectangle to capsule

**Comment by lmas3009** [comment]
perfect 💯

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
