### PR TITLE
Completed Design 29

### PR DESCRIPTION
**Pull request by abhayanand08**

### CODE REVIEW

**Comment by lmas3009** [comment]
Share the result screenshot

**Comment by abhayanand08** [comment]
> Share the result screenshot

Design

**Comment by lmas3009** [comment]
Great work @abhayanand08. This is looking good.

**Comment by lmas3009** [comment]
Thanks for your contribution 🤝

Merged

**Comment by abhayanand08** [comment]
> Great work @abhayanand08. This is looking good.

Thank You So much @lmas3009

**Pull request merged**
