### PR TITLE
Design 10

### PR DESCRIPTION
**Pull request by siddhant2002**
Created design 10

{68593169-EFA3-4B81-BE9A-DEEB00918EB3}

### CODE REVIEW

**Comment by siddhant2002** [comment]
@lmas3009 Please review. Thanks

**Comment by lmas3009** [comment]
Perfect!

Thanks for contributing 🤝

Submit the form to receive your stickers https://tally.so/r/nrdEkp
Please submit the form once all your PR's are merged.

**Review by lmas3009 — APPROVED** [review]

**Comment by lmas3009** [comment]
You can merge the code

**Comment by siddhant2002** [comment]
@lmas3009 I am unable to merge the code, Can you please merge the design file. Thanks

**Comment by lmas3009** [comment]
Merged

**Pull request merged**
