### PR TITLE
Creted Design 07🚀🚀

### PR DESCRIPTION
**Pull request by pratiksrivastava01**

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you attach a screenshot of the result in this PR

**Comment by pratiksrivastava01** [comment]
image

**Comment by lmas3009** [comment]
Good Work. Thanks for contributing @pratiksrivastava01

**Comment by lmas3009** [comment]
merged

**Comment by pratiksrivastava01** [comment]
Thank you @lmas3009

**Pull request merged**
