### PR TITLE
feat: Design 24

### PR DESCRIPTION
**Pull request by shraddha15-creator**
Added design 24- Food Delivery landing page

design24

### CODE REVIEW

**Comment by lmas3009** [comment]
Great. The design is looking good. Thanks for raising a PR and for your contribution 🤝

**Comment by lmas3009** [comment]
Can you add the issue ID

**Comment by shraddha15-creator** [comment]
> Can you add the issue ID

I don't know how to add, can you please tell me what to do?

**Comment by lmas3009** [comment]
Try to copy the #{id} which was assigned to you in "issue"

**Comment by shraddha15-creator** [comment]
> Try to copy the #{id} which was assigned to you in "issue"

#62

**Comment by lmas3009** [comment]
Merging the code

**Pull request merged**
