### PR TITLE
Created the design as specified

### PR DESCRIPTION
**Pull request by avyuktsoni0731**
Closes issue #132 

Made a design as similar as possible using HTML & CSS.

But facing an issue during rescaling of window (as it was optional to make webpage responsive).

[https://drive.google.com/file/d/1tIbJQfntX95AmH98AE2Yn8rM-7NAJ7kd/view?usp=sharing](url)

### CODE REVIEW

**Comment by lmas3009** [comment]
Responsive is optional. The output looks great. Can you use this font https://fonts.google.com/specimen/PT+Sans+Caption?query=pt+sans.

After this change it is ready to merge

**Comment by avyuktsoni0731** [comment]
Screenshot 2023-10-01 at 9 40 01 AM

**Comment by lmas3009** [comment]
Now it looks good. Thanks for your contribution

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
