### PR TITLE
Design 23_2023

### PR DESCRIPTION
**Pull request by Atrika10**
#158 completed. under hacktoberfest2023.

### CODE REVIEW

**Comment by Atrika10** [comment]
I'd be happy to get feedback after reviewing this PR.
cc : @imas3009

Thank you
Atrika

**Comment by lmas3009** [comment]
can you share the result screenshot

**Comment by Atrika10** [comment]
hey @lmas3009,
 I've attached a screenshot of the results for your review:
image

Your feedback and comments would be greatly appreciated. 
Please let me know your thoughts when you have a moment. 
Thank you!
Atrika

**Comment by lmas3009** [comment]
Perfect 👍

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Comment by Atrika10** [comment]
hello, @lmas3009, 
Thanks for merging this PR but may I know why it is showing a red cross after merging? It'd be very helpful if you give a brief description of this.
And I'm very Sorry for the late reply as I was busy with my admission process.

Thanks
Atrika

**Comment by lmas3009** [comment]
what do you mean by red cross after merging any screenshot

**Comment by Atrika10** [comment]
> what do you mean by red cross after merging any screenshot

sure.
this is what I mean to say
image

**Comment by lmas3009** [comment]
That is regarding the deployment and it is not related to your hacktoberfest pr

**Comment by Atrika10** [comment]
> That is regarding the deployment and it is not related to your hacktoberfest pr

Okay Thank you @lmas3009 for clearing my doubts. 
So this will not create any problem  in my hacktoberfest PR. Am i right??

**Comment by lmas3009** [comment]
No that is not a problem

**Comment by Atrika10** [comment]
> No that is not a problem 

Okay 👍
Actually, in my hacktoberfest profile,I am not able to see that 1 pr has been merged.
That's why I'm confused....

**Pull request merged**
