### PR TITLE
Design32

### PR DESCRIPTION
**Pull request by G0V1NDK**
Added the event planner website

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you share the result screenshot

**Comment by G0V1NDK** [comment]
Here is the Live preview of the website that I created.
Event Planner (g0v1ndk-event-planner.netlify.app)
<https://g0v1ndk-event-planner.netlify.app/>

**Comment by lmas3009** [comment]
Looking Great @G0V1NDK. Good work

**Comment by lmas3009** [comment]
Thanks for your contribution 🤝

merged

**Comment by G0V1NDK** [comment]
Thank you so much.

**Pull request merged**
