### PR TITLE
Added a BottleUp Design website

### PR DESCRIPTION
**Pull request by suprity04**

### CODE REVIEW

**Comment by suprity04** [comment]
@lmas3009 I have tried something new . Checkout my website design and please review it.

**Comment by suprity04** [comment]
@lmas3009 please go through my website once.

**Comment by suprity04** [comment]
hey! @lmas3009 you haven't seen my website yet please have a look over it I have tried something new.

**Comment by lmas3009** [comment]
Great work @suprity04. The design and website is looking good.

Thanks for your contribution 🤝

**Pull request merged**
