### PR TITLE
Design 29_2023

### LINKED ISSUE #164: 2023 Design 29
Create a folder with the Design 29_2023

Built it using HTML, CSS/Tailwind CSS, Javascript

Optional: Make it Responsive

Design by **Aravind Kumar Vemula**

## Design
design11-6

## Resources

fonts: https://fonts.google.com
colors: https://coolors.co
images: https://unsplash.com or https://www.pexels.com

### PR DESCRIPTION
**Pull request by Sugamgoel28**
Closes #164 

Developed the Design 29_2023 using HTML and CSS

final_design

### CODE REVIEW

**Comment by lmas3009** [comment]
perfect 💯

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Comment by Sugamgoel28** [comment]
Thank you for the wonderful repo. It's really fun. As you mentioned, more designs will be added today, and I would like to contribute more. Should I fill out the form for badges every time or can I fill it once all together?

**Comment by lmas3009** [comment]
You can fill all at once.

**Pull request merged**
