### PR TITLE
Added Wall Of Contributors to README.md

### PR DESCRIPTION
**Pull request by NagaJahnaviD**
Hey @Imas3009
I have added contibutors wall to README.
Do check it and merege.

#261

It is visible at the bottom end of the file.
Alse, consider giving my PR HactoberFest2024 asscepted
Screenshot 2024-10-24 185208

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you add a separate section for the organizer. Organizer is @intmone

**Comment by NagaJahnaviD** [comment]
yeah! sure

i ahve added it!
do check it out

**Comment by lmas3009** [comment]
Can you share the screenshot

**Comment by lmas3009** [comment]
Perfect!

Thanks for contributing 🤝

Submit the form to receive your stickers https://tally.so/r/nrdEkp
Please submit the form once all your PR's are merged.

**Review by lmas3009 — APPROVED** [review]

**Pull request merged**
