### PR TITLE
Add Design 37_2023 file

### PR DESCRIPTION
**Pull request by harshil-junakiya**
I have made a design and am also trying to make it responsive, but I have not had success.

### CODE REVIEW

**Comment by harshil-junakiya** [comment]
Screenshot (161)

**Comment by harshil-junakiya** [comment]
Hello @lmas3009 !
Review the changes

**Comment by lmas3009** [comment]
Perfect

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
