### PR TITLE
Created design as mentioned

### PR DESCRIPTION
**Pull request by Devesh1509**
@lmas3009  Created Design17_2023 as mentioned.
Please review and approve it.

### CODE REVIEW

**Comment by lmas3009** [comment]
screenshot of the output

**Comment by Devesh1509** [comment]
design17_2023

**Comment by lmas3009** [comment]
Can you change the text "embrace the majestrt of mountains" color to white

**Comment by Devesh1509** [comment]
> Can you change the text "embrace the majestrt of mountains" color to white
sure @lmas3009 , is this okay?
should i create PR now ?
desig17_2023

**Comment by lmas3009** [comment]
You can commit to this current PR itself

**Comment by Devesh1509** [comment]
> You can commit to this current PR itself

okay done.

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
