### PR TITLE
Completed Design 27

### PR DESCRIPTION
**Pull request by abhayanand08**

### CODE REVIEW

**Comment by lmas3009** [comment]
@abhayanand08  can you share the screenshot

**Comment by abhayanand08** [comment]
> @abhayanand08 can you share the screenshot

I have already added the screenshot in the folder

**Comment by lmas3009** [comment]
Thanks.

**Comment by lmas3009** [comment]
The design is looking good. Great work. 

Thanks for your contribution 🤝

**Comment by abhayanand08** [comment]
> Thanks.

Now just waiting for your approval @lmas3009

**Comment by abhayanand08** [comment]
> The design is looking good. Great work.
> 
> Thanks for your contribution 🤝

Thank you so much @lmas3009

**Comment by lmas3009** [comment]
merged

**Pull request merged**
