### PR TITLE
Created the design 🚀🚀

### PR DESCRIPTION
**Pull request by pratiksrivastava01**

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you share the result screenshot

**Comment by pratiksrivastava01** [comment]
image

**Comment by lmas3009** [comment]
I think one is Google and the other one is GitHub for authentication

**Comment by pratiksrivastava01** [comment]
it was on design 16

**Comment by lmas3009** [comment]
[!img](https://user-images.githubusercontent.com/60876387/193267585-2350a7bb-db50-4243-a532-7125adfafcf5.png)

**Comment by pratiksrivastava01** [comment]
Can you please explain

**Comment by lmas3009** [comment]
1. Sign in with Google
2. Sign in with GIthub
3. Sign in with Email

There should be three button with these names

**Comment by pratiksrivastava01** [comment]
oh yaa 
image
is this good

**Comment by lmas3009** [comment]
Have you update and pushed the code

**Comment by lmas3009** [comment]
Looking Good @pratiksrivastava01 Thanks for your contribution 🤝

**Comment by lmas3009** [comment]
Merged

**Pull request merged**
