### PR TITLE
Created Design

### PR DESCRIPTION
**Pull request by Nainish-Rai**
Created Design-11 , It is responsive ; Here is a screenshot
Screenshot from 2022-10-01 23-51-57

### CODE REVIEW

**Comment by lmas3009** [comment]
Which font have you used

**Comment by Nainish-Rai** [comment]
@lmas3009 I was unable to find the font used so I have used "impact" font. Can you tell me name of original font used so that I can change to it.

**Comment by lmas3009** [comment]
I used the Poppins font from fonts.google.com

**Comment by Nainish-Rai** [comment]
@lmas3009 I have fixed the font; Here is a screenshot, Kindly check
Screenshot from 2022-10-02 11-11-34

**Comment by lmas3009** [comment]
Looking Good.

**Comment by lmas3009** [comment]
Thanks for the contribution 🤝 @Nainish-Rai

**Pull request merged**
