### PR TITLE
Design 01_2023

### PR DESCRIPTION
**Pull request by SohamTamhane**
I have made the design using HTML, CSS. I have also made the website **Responsive**.
Please accept my pull request.

Thank You!

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you share the screenshot of the result

**Comment by SohamTamhane** [comment]
image
Screenshot of the Output Website

**Comment by lmas3009** [comment]
perfect 👍

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
