### PR TITLE
Created the website design given in #130 issue

### PR DESCRIPTION
**Pull request by saffi-786**
Created the website design given in #130  issue
Can you please review it
image

### CODE REVIEW

**Comment by lmas3009** [comment]
The output was good. But to use tailwindcss in HTML you can just use this https://tailwindcss.com/docs/installation/play-cdn

With this, you can just add one line of script task and that's it. Tailwindcss will work. 
It is not required to install a tailwind CSS npm package. 

Try this step and push the code again.

**Comment by saffi-786** [comment]
Sure. I'll do it and update.

**Comment by saffi-786** [comment]
Hey @lmas3009, I have updated the Design 05_2023 folder.
Please review it.

**Comment by lmas3009** [comment]
Can you share the screenshot of final image

**Comment by saffi-786** [comment]
Sure 
image

**Comment by lmas3009** [comment]
Perfect. Thanks for contributing

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Comment by saffi-786** [comment]
Thanks for merging the PR

**Pull request merged**
