### PR TITLE
design 23 added

### PR DESCRIPTION
**Pull request by Sahilbal**

### CODE REVIEW

**Comment by Sahilbal** [comment]
@lmas3009  kindly accept my PR. thank you!!

**Comment by lmas3009** [comment]
Can you share the result screenshot

**Comment by Sahilbal** [comment]
> Can you share the result screenshot

Screenshot of whole website?

**Comment by Sahilbal** [comment]
image
image
image
image
image

**Comment by Sahilbal** [comment]
is it fine now? @lmas3009

**Comment by lmas3009** [comment]
great @Sahilbal It's looking good. 

Thanks for your contribution 🤝

Merged

**Pull request merged**
