### PR TITLE
Design09#134

### PR DESCRIPTION
**Pull request by Pariharx7**

### CODE REVIEW

**Comment by Pariharx7** [comment]
Output screenshot

**Comment by lmas3009** [comment]
unable to view the output. can  you share it again

**Comment by Pariharx7** [comment]
Sure here it is

**Comment by lmas3009** [comment]
Perfect

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Comment by Pariharx7** [comment]
Thanks❤

Will look into the issues tab for new issues and to contribute ✌

**Pull request merged**
