### PR TITLE
Added a Python_Tutor design website

### PR DESCRIPTION
**Pull request by suprity04**

### CODE REVIEW

**Comment by suprity04** [comment]
@lmas3009 I have added a beautiful design please have a look of my PR.

**Comment by suprity04** [comment]
@lmas3009  Please go through my website design which I have added .

**Comment by suprity04** [comment]
hey! @lmas3009 you haven't checked my website yet please check it .

**Comment by lmas3009** [comment]
@suprity04 i can't see the code files in your commit
Try to update it and push it again

**Comment by suprity04** [comment]
@lmas3009  I have updated my PR have a look .

**Comment by lmas3009** [comment]
Great work @suprity04. The design, code, and website is looking good.

Thanks for your contribution 🤝

**Pull request merged**
