### PR TITLE
Design 04_2024

### PR DESCRIPTION
**Pull request by siddhant2002**
Design 04_2024

image

### CODE REVIEW

**Comment by siddhant2002** [comment]
@lmas3009 Please review the PR. Thanks

**Comment by siddhant2002** [comment]
@Imas3009 Please review the PR. Thanks

**Comment by siddhant2002** [comment]
@lmas3009, Please review the pr. Thanks

**Comment by lmas3009** [comment]
Perfect!

Thanks for contributing 🤝

Submit the form to receive your stickers https://tally.so/r/nrdEkp
Please submit the form once all your PR's are merged.

**Review by lmas3009 — APPROVED** [review]

**Pull request merged**
