### PR TITLE
Added an e-commerce_Laptop Website

### PR DESCRIPTION
**Pull request by suprity04**

### CODE REVIEW

**Comment by suprity04** [comment]
@lmas3009 I've added the website ,you can go through it.

**Comment by suprity04** [comment]
@lmas3009 Kindly check my PR .I've added the website design please give a look to it .

**Comment by lmas3009** [comment]
Great work @suprity04 👍. The website and design is looking good

**Comment by lmas3009** [comment]
Thanks for your contribution 🤝

Merged

**Pull request merged**
