### PR TITLE
[Feature]:Added a new Design

### LINKED ISSUE #140: 2023 Design 15
Create a folder with the Design 15_2023

Built it using HTML, CSS/Tailwind CSS, Javascript

Optional: Make it Responsive

Design by **Aravind Kumar Vemula**

## Design
MacBook Pro 16_ - 19

## Resources

fonts: https://fonts.google.com
colors: https://coolors.co
images: https://unsplash.com or https://www.pexels.com

### PR DESCRIPTION
**Pull request by Rohit-Sharmaa**
#Description
This pr makes the design according to the issue
Fixes #140

Design
Screenshot 2023-10-01 094002

### CODE REVIEW

**Comment by Rohit-Sharmaa** [comment]
@lmas3009 review my code.

**Comment by lmas3009** [comment]
Can you use this font https://fonts.google.com/specimen/PT+Sans+Caption?query=pt+sans and the website look good. ready to merge after this change

**Comment by Rohit-Sharmaa** [comment]
@lmas3009 yah sure

**Review by Rohit-Sharmaa — COMMENTED** [review]
added new font and padding

**Comment by Rohit-Sharmaa** [comment]
@lmas3009 
Screenshot 2023-10-01 100339

How it is now ??

**Comment by lmas3009** [comment]
For the cards can you add padding left.

**Comment by Rohit-Sharmaa** [comment]
@lmas3009  I have already added padding left but in the screenshot it is not visible 
here is the updated screenshot 
Screenshot 2023-10-01 102003

if you need more padding just let me know ??

**Comment by lmas3009** [comment]
perfect

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
