### PR TITLE
Added a health related website

### PR DESCRIPTION
**Pull request by abhayanand08**

### CODE REVIEW

**Comment by lmas3009** [comment]
Can u share the result screenshot

**Comment by abhayanand08** [comment]
> Can u share the result screenshot

Design1 (1)
Design1 (2)
Design1 (3)

**Comment by lmas3009** [comment]
Great design @abhayanand08 the website is looking good.


Thanks for your contribution 🤝

**Comment by lmas3009** [comment]
Merged

**Comment by abhayanand08** [comment]
> Great design @abhayanand08 the website is looking good.
> 
> Thanks for your contribution 🤝

Thank you so much.

**Pull request merged**
