### PR TITLE
Flipkart clone

### PR DESCRIPTION
**Pull request by SahilJin123**
Plz merge Flipkart Clone .  As you have told that we can merge shopping website clone in comments in Design 35.

### CODE REVIEW

**Comment by lmas3009** [comment]
For design 35 some other person is working on it.
So try to create a new folder with flipkart_clone and push it

**Comment by SahilJin123** [comment]
I have pushed it

**Comment by lmas3009** [comment]
Share your result screenshot

**Comment by SahilJin123** [comment]
Sure, here it is.

**Comment by SahilJin123** [comment]
f1
f2
f3

**Comment by SahilJin123** [comment]
Plz  add this to your Repo and Provide me with Hacktoberfest Accepted Tag.

**Comment by lmas3009** [comment]
Its looking good great work @SahilJin123. Thanks for your contribution 🤝

**Pull request merged**
