### PR TITLE
design 60 by iceXshadow inspired from dribbble

### PR DESCRIPTION
**Pull request by iceXshadow**

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you share the result screenshot

**Comment by iceXshadow** [comment]
Yes I will share shortly

**Comment by iceXshadow** [comment]
> Can you share the result screenshot

design60_1
design60_2

**Comment by iceXshadow** [comment]
Sorry for the delay

**Comment by lmas3009** [comment]
Perfect

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
