### PR TITLE
2023 Design 02 Multi PR accepted #127 issue resolved

### PR DESCRIPTION
**Pull request by praptisharma28**
Made a similar webpage design as suggested by you into the folder name as per rules, hope you like it! 
If you merge my PR, please give me the (hacktober-accepted) tag so that it counts as my contribution to Hacktoberfest. Thankyou for reading!

### CODE REVIEW

**Comment by lmas3009** [comment]
can you share the screenshot

**Comment by lmas3009** [comment]
Remove { } this before and after your name. In the folder

**Comment by praptisharma28** [comment]
Sure @lmas3009

**Comment by lmas3009** [comment]
Perfect. Thanks for contributing

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Comment by TANYA03GUPTA** [comment]
@praptisharma28  Could you tell me if this repo is accepted in the official website or is it excluded?

**Comment by lmas3009** [comment]
It will get accepted. You need to wait for 7 days after your pr got merged. To know your first contribution is done.

7days is the waiting time for after pr got merged from hacktoberfest

**Comment by praptisharma28** [comment]
Hey @TANYA03GUPTA , it is not excluded, its in the waiting period on my profile. Hoping @lmas3009 's comment helps!

**Pull request merged**
