### PR TITLE
Create design 01 landing page issue #126

### LINKED ISSUE #126: 2023 Design 01 Multi Assignees accepted
Create a folder with the Design 01_2023/{yourname}

Built it using HTML, CSS/Tailwind CSS, Javascript

Optional: Make it Responsive

Note: Add your images, about, live github/dev.to links. **PART 1**
Design 02 is **PART 2**

We accept multiple PR's. This is your personal website. 

**✨✨Do not add the same text as shown**

Design by **Aravind Kumar Vemula**

## Design
MacBook Pro 16_ - 3

## Resources

fonts: https://fonts.google.com
colors: https://coolors.co
images: https://unsplash.com or https://www.pexels.com

### PR DESCRIPTION
**Pull request by purnasth**
# Pull Request: Completing Design 01 Landing Page Development - Issue #126

## Description
This pull request addresses and completes the work outlined in issue #126, where we were tasked with developing the landing page based on the provided design.

## Changes Made
1. **Landing Page Development**: Developed the landing page according to the provided design guidelines.
2. **Content Integration**: Incorporated my information, ensuring that it is accurately presented on the page.
3. **Responsive Design**: Ensured the landing page was responsive and functions well across various devices and screen sizes.
4. **Optimized Assets**: Compressed and optimized images and assets to enhance loading speed.

## Screenshots (if applicable)
image

## Additional Notes
- The development of the landing page is complete and aligns with the design specifications provided in issue #126.
- Please review the changes and the overall appearance of the landing page, and feel free to provide any feedback or suggestions for improvement.

Closes #126

### CODE REVIEW

**Comment by lmas3009** [comment]
You can use this https://tailwindcss.com/docs/installation/play-cdn apart from using this
image

**Comment by purnasth** [comment]
Previously, I was using ply-cdn for tailwindCSS setup but sadly, this causes the following error to appear on the console. The error message is indicating that using the CDN (Content Delivery Network) version of Tailwind CSS is not recommended for production use. Instead, it advises you to install Tailwind CSS as a PostCSS plugin or use the Tailwind CLI for production use.

image

**Comment by purnasth** [comment]
Hi there, @lmas3009 the 01 design landing page is prepared for merging. You should review this PR right away. and I could begin working on my second issue.

**Comment by lmas3009** [comment]
Okay

**Comment by lmas3009** [comment]
Perfect

Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
