### PR TITLE
Added HotelBookingPage

### PR DESCRIPTION
**Pull request by KrishnaChaitanya1822**
Hotel Booking Page

### CODE REVIEW

**Comment by lmas3009** [comment]
Add a screenshot of your result

**Comment by KrishnaChaitanya1822** [comment]
image

**Comment by lmas3009** [comment]
Add Poppins fonts for all the text. It might good look

**Comment by KrishnaChaitanya1822** [comment]
Is it ok?
image

**Comment by lmas3009** [comment]
Looking good. Thanks for the contribution 🤝

**Comment by lmas3009** [comment]
Metged

**Comment by KrishnaChaitanya1822** [comment]
wait, I have to change the code in the design 36 folder also

**Comment by lmas3009** [comment]
Yes you can push it again

**Pull request merged**
