### PR TITLE
Design 54

### PR DESCRIPTION
**Pull request by Anand-shreya**
sir here is my work hope you like it if you want any changes kindly let me know otherwise accept my PR for Design 54. thank you

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you share the result screenshot

**Comment by Anand-shreya** [comment]
Screenshot (172)

**Comment by lmas3009** [comment]
Great work @Anand-shreya Its looking good.

Thanks for your contribution 🤝

**Comment by Anand-shreya** [comment]
@lmas3009 please have a look at PR #116

**Pull request merged**
