### PR TITLE
Design12_Issue-#12

### PR DESCRIPTION
**Pull request by hparihar-07**
I have code the design that you have mentioned in the issue-12 .I also have added a basic animation so that the text looks amazing 🤩

### CODE REVIEW

**Comment by lmas3009** [comment]
Can you share the output screenshot

**Comment by hparihar-07** [comment]
I have uploaded it on a free hosting site to see how it looks you can check it too 
[check here](birdy00.prohosts.org)

**Comment by lmas3009** [comment]
Perfect It looks great

**Comment by lmas3009** [comment]
Merged 🚀

Submit this form to receive badges
https://tally.so/r/mOXlRR

**Pull request merged**
